package vn.attendance.util;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum MessageCode implements MessageCodeEnum {
    NOT_FOUND("Not Found"),
    ROLE_NOT_FOUND("Role Not Found"),
    USERNAME_NOT_FOUND("Username Not Found"),
    USER_NOT_FOUND("User Not Found"),
    CAMERA_NOT_EVENT("The camera does not have a face comparison feature!"),
    LOGIN_FAIL("Username or password incorrect"),
    OTP_EXPIRED("Opt is incorrect or expired!"),
    OLD_PASSWORD_NOT_MATCH("Old password not match with current password!"),
    TOKEN_EXPIRE("Token expire!"),
    USERNAME_ALREADY_EXISTS("Username already exists!"),
    EMAIL_ALREADY_EXISTS("Email already exists!"),
    DISK_STATE_FAIL("Unable to retrieve disk state!"),
    CAMERA_INFO_FAIL("Unable to retrieve camera information!"),
    SERVER_CONNECT_FAIL("Unable to connect to the server!"),
    EXPORT_FAIL("Export file failed!"),
    CONTENT_EMPTY("No data is returned!"),
    ADD_USER_FAIL("Add User Fail!"),
    ADD_CAMERA_FAIL("Add Camera Fail!"),
    USER_NOT_AUTHORITY("User not authority!"),
    FORMAT_FAIL("Format failed!"),
    SUBJECT_CODE_ALREADY_EXISTS("Subject code already exists."),
    SUBJECT_NAME_ALREADY_EXISTS("Subject name already exists!"),
    ADD_SUBJECT_FAIL("Add Subject Fail!"),
    ROOM_ALREADY_EXISTS("Room already exists!"),
    ADD_ROOM_FAIL("Add room fail"),
    PHONE_ALREADY_EXISTS("Phone already exists!"),
    CAMERAROOM_ALREADY_EXISTED("Camera Room already exists!"),
    ADD_SEMESTER_FAIL("Add Semester Fail!"),
    ADD_CAMERAROOM_FAIL("Add Camera Room Fail!"),
    ADD_CLASSROOM_FAIL("Add ClassRoom Fail!"),
    UPDATE_USER_FACE_FAIL("Update Face Fail!"),
    ADD_USER_FACE_FAIL("Add Face Fail!"),
    DELETE_USER_FACE_FAIL("Delete Face Fail!"),
    DELETE_CAMERA_FAIL("Delete Camera Fail!"),
    INVALID_TIME_RANGE("Invalid Time Range!"),
    SEMESTER_ALREADY_EXISTS("Semester already exists!"),
    SCHEDULE_ALREADY_EXISTS("Schedule already exists!"),
    TIMESLOT_ALREADY_EXISTS("Timeslot already exists!"),
    CLASSNAME_ALREADY_EXISTED("Class already exists!"),
    CURRICULUM_NAME_EXIST("Curriculum already exists!"),
    SCHEDULE_FAILED_SUBJECT("The schedule has a different subject!"),
    SCHEDULE_FAILED_CLASS("The schedule has a different class!"),
    SCHEDULE_FAILED_TEACHER("The schedule has a different teacher!"),
    SCHEDULE_FAILED_CLASS_TIME("The schedule has a different class in timeslot!"),
    ROOM_NOT_FOUND("Room not found!"),
    CLASS_NOT_FOUND("Class not found!"),
    TIMESLOT_NOT_FOUND("TimeSlot not found!"),
    SUBJECT_NOT_FOUND("Subject not found!"),
    CAMERAROOM_NOT_FOUND("Camera Room not found!"),
    CAMERA_NOT_FOUND("Camera not found!"),
    CLASSROOM_NOT_FOUND("Classroom not found!"),
    CURRICULUM_NOT_FOUND("Curriculum not found!"),
    CURRICULUMSUB_NOT_FOUND("Curriculum Subject Not Found"),
    CURRICULUMSUB_NO_CHANGES("No changes was made to this Curriculum Subject"),
    CURRICULUMSUB_ALREADY_EXISTED("Curriculum Subject Already existed"),
    STUDENT_CLASS_NOT_FOUND("Student class not found!"),
    STUDENT_NOT_FOUND("Student not found!"),
    STUDENT_CLASS_EXISTED("Student class existed!"),
    DELETE_STUDENT_CLASS_FAIL("Delete student class fail!"),
    ADD_STUDENT_CLASS_FAIL("Add student class fail!"),
    UPDATE_CAMERA_FAIL("Update camera fail!"),
    STUDENT_ALREADY_HAVE_CURRICULUM("Student already have curriculum"),
    STUDENT_DOES_NOT_HAVE_CURRICULUM("Student does not have curriculum"),
    SEMESTER_NOT_FOUND("Semester not found!"),
    SCHEDULE_NOT_FOUND("Schedule not found!"),
    ATTENDANCE_NOT_FOUND("Attendance not found!"),
    CAMERA_ALREADY_EXISTED("Camera already exists!"),
    CLASS_SUBJECT_EXISTED("Class subject existed!"),
    ADD_CLASS_SUBJECT_FAIL("Add class subject fail!"),
    CLASS_SUBJECT_NOT_FOUND("Class subject not found!"),
    CHECK_ATTEND_INVALID_TIME("Data changes must be made before 00:00 today!");
    private final String code;
}
